<!--Obsah-->
<article><h3>Kdo jsme...</h3>
  <div class="clearfix"><img src="foto/jh_foto.jpg" alt="Jan Havel" title="Jan Havel" id="profiljh"><p><strong class="marked">Jan Havel</strong> dolor sit amet, consectetuer adipiscing elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam ligula pede, sagittis quis, interdum ultricies, scelerisque eu. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam id dolor. Nulla quis diam. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Nulla est. Etiam egestas wisi a erat. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Proin in tellus sit amet nibh dignissim sagittis. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Pellentesque arcu. In laoreet, magna id viverra tincidunt, sem odio bibendum justo, vel imperdiet sapien wisi sed libero.
  </p>
  </div>
  
  <div class="clearfix"><img src="foto/jv_foto.jpg" alt="Jan Vejvoda" title="Jan Vejvoda" id="profiljv"><p>Curabitur <strong class="marked">Jan Vejvoda</strong>, pulvinar a vestibulum quis, facilisis vel sapien. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Donec quis nibh at felis congue commodo. Nunc dapibus tortor vel mi dapibus sollicitudin. Sed elit dui, pellentesque a, faucibus vel, interdum nec, diam. In enim a arcu imperdiet malesuada. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam sapien elit, consequat eget, tristique non, venenatis quis, ante. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Nullam lectus justo, vulputate eget mollis sed, tempor sed magna. Proin mattis lacinia justo. Aliquam ante. Integer malesuada. Etiam dui sem, fermentum vitae, sagittis id, malesuada in, quam. Etiam bibendum elit eget erat. Nam sed tellus id magna elementum tincidunt. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Duis pulvinar.
  </p>
  </div>
</article>
<article>
<h3>Co je naším posláním...</h3>
  <p>Nunc auctor. Nullam sit amet magna in magna gravida vehicula. Duis condimentum augue id magna semper rutrum. Integer malesuada. Suspendisse nisl. Morbi leo mi, nonummy eget tristique non, rhoncus non leo. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis condimentum augue id magna semper rutrum. Nullam faucibus mi quis velit. Nullam rhoncus aliquam metus. Nam quis nulla. Vivamus luctus egestas leo.
  </p>
</article>