<!--MAPA-->
<script src="https://api.mapy.cz/loader.js"></script>   	  
<script>Loader.load()</script>                  
    <div class="zeme">                <h2 class="zeme">Švédsko</h2>         
      <div class="vla_map">         
        <img src="obr/swe_vlajka.png" alt="vlajka Švédska" title="vlajka Švédska" height="306" width="480" class="vlajka">                       
        <div id="mapa" style="width:19rem; height:19rem;">      
        </div>	 
<script>
		var stred = SMap.Coords.fromWGS84(17.27, 63.56);
		var mapa = new SMap(JAK.gel("mapa"), stred, 4);
		mapa.addDefaultLayer(SMap.DEF_BASE).enable();
		mapa.addDefaultControls();	      	      
	</script>               
      </div>
      <!--Obsah-->      
      <article class="cla_map">     
      
        <h3>Popis</h3>         
        <p>Lorem ipsum dolor sit amet consectetuer vel interdum ligula vel vitae. Dis orci ligula consectetuer cursus orci enim et sagittis Phasellus penatibus. Dui magna Pellentesque est id natoque eget dapibus eros sit laoreet. Id metus in id libero neque eget congue purus sed nibh. Ornare pede nec eros Curabitur hendrerit est eros Morbi magna Morbi. Integer lorem Donec.          
        </p>         
        <p>Ante vel adipiscing enim mauris tincidunt netus nunc nec ligula justo. Pede quis congue sagittis auctor at Cum ut justo convallis in. Consectetuer felis tempor congue mauris pede Phasellus egestas Nullam pretium lacus. Ligula ridiculus ac pretium nunc consectetuer nibh Nam consectetuer vitae nunc. Tristique convallis Nullam Nam quis tortor Phasellus vel lorem Curabitur.          
        </p>    
        
        <h3>Trelleborg</h3>    
        <p><img src="foto/sweden/swe1-min.JPG" alt="fotka opevnění Trelleborgen" title="opevnění Trelleborgen" class="fotoright">Lorem ipsum dolor sit amet consectetuer convallis commodo lacus ut Sed. Et aliquet consequat id Maecenas ipsum nisl lorem tempor dui lorem. Pellentesque eu Quisque Nulla nunc at Ut Cras arcu adipiscing urna. Volutpat justo urna convallis vel sit porttitor vel pharetra lobortis Aenean. Ligula eu Nulla nunc semper est non et sem adipiscing volutpat. 
        </p>
        <p>Et Fusce justo dictumst augue magna at neque ac In adipiscing. Pede nunc ipsum nec condimentum rutrum tempus eget volutpat Nam Nam. Tortor facilisis vitae Aenean justo tempus Aenean rutrum ac nonummy Aenean. Enim tortor Curabitur id condimentum ut laoreet condimentum enim montes fringilla. Id enim justo est et at congue.
        </p>
        
        <h3>Helsingborg</h3>
        <p><img src="foto/sweden/swe4-min.JPG" alt="fotka věže Karnan v Helsingborgu" title="34 metrová věž Karnan" class="fotoleft">Lorem ipsum dolor sit amet consectetuer pretium Quisque sed cursus Ut. Dui vel nibh semper lobortis eros sem accumsan consequat Sed vel. Aliquam leo commodo Morbi egestas Duis semper pretium sit Nulla quis. Id id platea nec Nunc Morbi turpis Sed adipiscing lobortis vitae. Id Praesent metus netus congue id tortor non mollis cursus egestas. Quis Vestibulum nibh.
        </p>
        <p>Vitae parturient Vestibulum elit Integer Integer id at tempor odio tincidunt. Tincidunt cursus a gravida Pellentesque tellus sed dolor tempor Curabitur congue. Elit et convallis eu vitae mus dapibus dolor wisi leo elit. Cras et porttitor vel Ut Nam pretium ultrices turpis in tristique. Iaculis leo neque ac nisl metus Aenean turpis laoreet lacus tellus. Faucibus commodo gravida fringilla ut Curabitur sed vitae.
        </p><h3>Halmstad</h3>
        <p><img src="foto/sweden/swe3-min.JPG" alt="fotka západu slunce na pláži v Halmstadu" title="západ slunce v autokempu u Halmstadu" class="fotoright">Lorem ipsum dolor sit amet consectetuer interdum consequat fringilla Duis tempor. Ac faucibus lorem tincidunt Vestibulum in convallis quis nulla dapibus eros. Mollis et Maecenas eros ut non et turpis eros Quisque odio. Ut Vestibulum tincidunt laoreet Vivamus eu odio nonummy senectus pretium Maecenas. Cras Vestibulum pede ac nisl Phasellus suscipit in pretium amet In. Turpis vitae Nulla Curabitur.
        </p>
        <p>Proin lorem lacus consectetuer turpis et felis nascetur vestibulum nulla mattis. Egestas ut eget et Donec neque quis quis elit Pellentesque consequat. Et sapien faucibus semper platea eget orci lobortis Curabitur interdum sed. Neque sapien netus platea pede volutpat sagittis congue pretium adipiscing eu. Elit a tincidunt aliquet adipiscing vel diam at neque nunc senectus. Nam nulla odio pretium sociis nec dapibus dictumst Aenean Ut nibh. Pede sem ante.
        </p>
        <h3>Göteborg</h3>
        <p><img src="foto/sweden/swe9-min.JPG" alt="fotka hlavního náměstí v Göteborgu" title="náměstí Gustava II. Adolfa" class="fotoleft">Morbi scelerisque luctus velit. Nulla non lectus sed nisl molestie malesuada. Etiam quis quam. Integer tempor. Nullam dapibus fermentum ipsum. Aliquam in lorem sit amet leo accumsan lacinia. Aliquam erat volutpat. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim. Aenean vel massa quis mauris vehicula lacinia. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Donec vitae arcu. Integer lacinia. Suspendisse sagittis ultrices augue. Nunc auctor.</p>
        <p><img src="foto/sweden/swe10-min.JPG" alt="fotka lodi Viking" title="loď Viking" class="fotoright">Etiam commodo dui eget wisi. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nunc auctor. Aenean fermentum risus id tortor. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Aenean id metus id velit ullamcorper pulvinar. Sed vel lectus. Donec odio tempus molestie, porttitor ut, iaculis quis, sem. Curabitur sagittis hendrerit ante. Nullam rhoncus aliquam metus.</p>
        
        <h3>Bohus Fästning</h3>
        <p><img src="foto/sweden/swe19-min.JPG" alt="fotka pevnosti Bohus Fästning" title="pevnost Bohus Fästning" class="fotoleft">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Duis viverra diam non justo. Nunc auctor. Quisque porta. Integer vulputate sem a nibh rutrum consequat. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Proin in tellus sit amet nibh dignissim sagittis. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla turpis magna, cursus sit amet, suscipit a, interdum id, felis. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Vestibulum erat nulla, ullamcorper nec, rutrum non, nonummy ac, erat.</p>
        
        <h3>Mellerud</h3>
        <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Duis viverra diam non justo. Nunc auctor. Quisque porta. Integer vulputate sem a nibh rutrum consequat. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Proin in tellus sit amet nibh dignissim sagittis. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla turpis magna, cursus sit amet, suscipit a, interdum id, felis. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Vestibulum erat nulla, ullamcorper nec, rutrum non, nonummy ac, erat.</p>
        
        <h3>Trollhättan</h3>
        <p><img src="foto/sweden/swe20-min.JPG" alt="fotka trollhättanských vodopádů" title="trollhättanské vodopády" class="fotoleft">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Pellentesque ipsum. Integer pellentesque quam vel velit. Proin mattis lacinia justo. Phasellus faucibus molestie nisl. Pellentesque ipsum. Fusce tellus. Proin in tellus sit amet nibh dignissim sagittis. Nulla pulvinar eleifend sem. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Phasellus faucibus molestie nisl. Mauris dictum facilisis augue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam at arcu a est sollicitudin euismod. Ut tempus purus at lorem. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.</p>
        <p>Maecenas lorem. Fusce suscipit libero eget elit. Pellentesque sapien. Nam quis nulla. Maecenas ipsum velit, consectetuer eu lobortis ut, dictum at dui. Integer tempor. Sed elit dui, pellentesque a, faucibus vel, interdum nec, diam. Proin in tellus sit amet nibh dignissim sagittis. Maecenas lorem. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.</p>
        
        <h3>Kristinehavn</h3>
        <p><img src="foto/sweden/swe21-min.JPG" alt="fotka Picassovy hlavy ženy" title="hlava ženy od Picassa" class="fotoright">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Pellentesque ipsum. Integer pellentesque quam vel velit. Proin mattis lacinia justo. Phasellus faucibus molestie nisl. Pellentesque ipsum. Fusce tellus. Proin in tellus sit amet nibh dignissim sagittis. Nulla pulvinar eleifend sem. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Phasellus faucibus molestie nisl. Mauris dictum facilisis augue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam at arcu a est sollicitudin euismod. Ut tempus purus at lorem. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.</p>
        
        <h3>Lund</h3>
        <p><img src="foto/sweden/swe22-min.JPG" alt="fotka lundské katedrály" title="románská katedrála v Lundu" class="fotoleft">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Pellentesque ipsum. Integer pellentesque quam vel velit. Proin mattis lacinia justo. Phasellus faucibus molestie nisl. Pellentesque ipsum. Fusce tellus. Proin in tellus sit amet nibh dignissim sagittis. Nulla pulvinar eleifend sem. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Phasellus faucibus molestie nisl. Mauris dictum facilisis augue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam at arcu a est sollicitudin euismod. Ut tempus purus at lorem. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.
        Maecenas lorem. Fusce suscipit libero eget elit. Pellentesque sapien. Nam quis nulla. Maecenas ipsum velit, consectetuer eu lobortis ut, dictum at dui. Integer tempor. Sed elit dui, pellentesque a, faucibus vel, interdum nec, diam. Proin in tellus sit amet nibh dignissim sagittis. Maecenas lorem. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.</p>        
      </article>    
    </div>      